-- Drop old tables if they exist to start fresh
drop table if exists public.files;
drop table if exists public.sources;
drop table if exists public.directories;

-- Create table for storing FTP sources
create table public.sources (
  id bigint generated by default as identity primary key,
  label text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for storing indexed DIRECTORIES
create table public.directories (
  id bigint generated by default as identity primary key,
  source_id bigint references public.sources(id) on delete cascade,
  name text not null,
  path text not null,
  original_link text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (source_id, path)
);

-- Admin Settings table (Stores hashed password)
create table public.admin_settings (
  id bigint generated by default as identity primary key,
  password_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.admin_settings enable row level security;
create policy "Enable all access for all users" on public.admin_settings for all using (true) with check (true);

-- Enable RLS
alter table public.sources enable row level security;
alter table public.directories enable row level security;

-- Create policies
create policy "Enable all access for all users" on public.sources for all using (true) with check (true);
create policy "Enable all access for all users" on public.directories for all using (true) with check (true);
